//
//  Node.swift
//  Down
//
//  Created by John Nguyen on 07.04.19.
//

import Foundation
import libcmark

/// A node is a wrapper of a raw `CMarkNode` belonging to the abstract syntax tree
/// generated by cmark.

public protocol Node: AnyObject {

    var parent: Node? { get }

    /// The wrapped node.

    var cmarkNode: CMarkNode { get }

    /// The wrapped child nodes.

    var children: [Node] { get }

}

public extension Node {

    /// True iff the node has a sibling that succeeds it.

    var hasSuccessor: Bool {
        return cmark_node_next(cmarkNode) != nil
    }

    /// Sequence of wrapped child nodes.

    var childSequence: ChildSequence {
        return ChildSequence(node: self, cmarkNode: cmarkNode)
    }

}

// MARK: - Helper extensions

public typealias CMarkNode = UnsafeMutablePointer<cmark_node>

public extension CMarkNode {

    /// Wraps the cmark node referred to by this pointer.

    func wrap(parent: Node?) -> Node? {
        switch type {
        case CMARK_NODE_DOCUMENT:       return Document(parent: parent, cmarkNode: self)
        case CMARK_NODE_BLOCK_QUOTE:    return BlockQuote(parent: parent, cmarkNode: self)
        case CMARK_NODE_LIST:           return List(parent: parent, cmarkNode: self)
        case CMARK_NODE_ITEM:           return Item(parent: parent, cmarkNode: self)
        case CMARK_NODE_CODE_BLOCK:     return CodeBlock(parent: parent, cmarkNode: self)
        case CMARK_NODE_HTML_BLOCK:     return HtmlBlock(parent: parent, cmarkNode: self)
        case CMARK_NODE_CUSTOM_BLOCK:   return CustomBlock(parent: parent, cmarkNode: self)
        case CMARK_NODE_PARAGRAPH:      return Paragraph(parent: parent, cmarkNode: self)
        case CMARK_NODE_HEADING:        return Heading(parent: parent, cmarkNode: self)
        case CMARK_NODE_THEMATIC_BREAK: return ThematicBreak(parent: parent, cmarkNode: self)
        case CMARK_NODE_TEXT:           return Text(parent: parent, cmarkNode: self)
        case CMARK_NODE_SOFTBREAK:      return SoftBreak(parent: parent, cmarkNode: self)
        case CMARK_NODE_LINEBREAK:      return LineBreak(parent: parent, cmarkNode: self)
        case CMARK_NODE_CODE:           return Code(parent: parent, cmarkNode: self)
        case CMARK_NODE_HTML_INLINE:    return HtmlInline(parent: parent, cmarkNode: self)
        case CMARK_NODE_CUSTOM_INLINE:  return CustomInline(parent: parent, cmarkNode: self)
        case CMARK_NODE_EMPH:           return Emphasis(parent: parent, cmarkNode: self)
        case CMARK_NODE_STRONG:         return Strong(parent: parent, cmarkNode: self)
        case CMARK_NODE_LINK:           return Link(parent: parent, cmarkNode: self)
        case CMARK_NODE_IMAGE:          return Image(parent: parent, cmarkNode: self)
        default:                        return nil
        }
    }

    var parent: CMarkNode? {
        return cmark_node_parent(self)
    }

    var next: CMarkNode? {
        return cmark_node_next(self)
    }

    var previous: CMarkNode? {
        return cmark_node_previous(self)
    }

    var type: cmark_node_type {
        return cmark_node_get_type(self)
    }

    var literal: String? {
        return String(cString: cmark_node_get_literal(self))
    }

    var fenceInfo: String? {
        return String(cString: cmark_node_get_fence_info(self))
    }

    var headingLevel: Int {
        return Int(cmark_node_get_heading_level(self))
    }

    var listType: cmark_list_type {
        return cmark_node_get_list_type(self)
    }

    var listStart: Int {
        return Int(cmark_node_get_list_start(self))
    }

    var listDelimiter: cmark_delim_type {
        return cmark_node_get_list_delim(self)
    }

    var url: String? {
        return String(cString: cmark_node_get_url(self))
    }

    var title: String? {
        return String(cString: cmark_node_get_title(self))
    }

    var startLine: Int {
        return Int(cmark_node_get_start_line(self))
    }

    var endLine: Int {
        return Int(cmark_node_get_end_line(self))
    }

    var startColumn: Int {
        return Int(cmark_node_get_start_column(self))
    }

    var endColumn: Int {
        return Int(cmark_node_get_end_column(self))
    }
}

extension CMarkNode: Equatable {
    public static func == (lhs: CMarkNode, rhs: CMarkNode) -> Bool {
        lhs.parent == rhs.parent &&
        lhs.previous == rhs.previous &&
        lhs.type == rhs.type &&
        lhs.literal == rhs.literal &&
        lhs.fenceInfo == rhs.fenceInfo &&
        lhs.headingLevel == rhs.headingLevel &&
        lhs.listType == rhs.listType &&
        lhs.listStart == rhs.listStart &&
        lhs.listDelimiter == rhs.listDelimiter &&
        lhs.url == rhs.url &&
        lhs.title == rhs.title &&
        lhs.startLine == rhs.startLine &&
        lhs.endLine == rhs.endLine &&
        lhs.startColumn == rhs.startColumn &&
        lhs.endColumn == rhs.endColumn
    }
}

private extension String {

    init?(cString: UnsafePointer<Int8>?) {
        guard let unwrapped = cString else { return nil }
        let result = String(cString: unwrapped)
        guard !result.isEmpty else { return nil }
        self = result
    }

}
